on:
  workflow_call:
name: semantic-check
jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm install -g @commitlint/cli @commitlint/config-conventional
      - run: "echo 'module.exports = {extends: [\"@commitlint/config-conventional\"]}' > commitlint.config.js"
      - run: npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose
