on:
  workflow_call:

name: semantic-check
jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 16
      - name: commitlint (install)
        run: |
          npm install -g @commitlint/cli @commitlint/config-conventional
          echo 'module.exports = {extends: ["@commitlint/config-conventional"]}' > commitlint.config.js
      - name: commitlint (run)
        run: npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose
