on:
  workflow_call:
name: terraform-security
jobs:
  terraform-security:
    runs-on: ubuntu-latest
    name: check if terraform config matches security standards
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: .
          framework: terraform
          download_external_modules: true
          quiet: true
      
