on:
  workflow_call:

name: terraform-docs
jobs:
  terraform-docs:
    runs-on: ubuntu-latest
    name: update docs
    steps:
      - name: checkout
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4
      - name: terraform-docs
        uses: terraform-docs/gh-actions@e47bfa196e79fa50987ef391be236d9d97b0c786 # v1.2.0
        with:
          working-dir: .
          output-file: README.md
          output-method: inject
          git-commit-message: "docs: update terraform docs"
          git-push: "true"
