on:
  workflow_call:

name: terraform-docs
jobs:
  terraform-docs:
    runs-on: ubuntu-latest
    name: update docs
    steps:
      - name: checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - name: terraform-docs
        uses: terraform-docs/gh-actions@7a62208a0090636af2df1b739da46d27fd90bdc6 # v1.1.0
        with:
          working-dir: .
          output-file: README.md
          output-method: inject
          git-commit-message: "docs: update terraform docs"
          git-push: "true"
