name: Terraform quality

on: push
jobs:
  terraform-lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.workdir }}
    steps:
      - name: checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - name: tfswitch
        run: |
          wget https://raw.githubusercontent.com/warrensbox/terraform-switcher/release/install.sh
          chmod 755 install.sh
          ./install.sh -b ./.bin v1.1.1 # Last arg is the desired tfswitch version
          rm install.sh
          .bin/tfswitch -b .bin/terraform
          .bin/terraform -v
