on:
  workflow_call:
    inputs:
      workdir:
        required: false
        type: string
        default: .
      checkov_enabled:
        required: false
        type: boolean
        default: true

name: terraform-quality
jobs:
  terraform-lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.workdir }}
    steps:
      - name: checkout
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
      - name: tfswitch
        run: |
          wget https://raw.githubusercontent.com/warrensbox/terraform-switcher/release/install.sh
          chmod 755 install.sh
          ./install.sh -b ./.bin 0.13.1288 # Last arg is the desired tfswitch version
          rm install.sh
          .bin/tfswitch -b .bin/terraform
          .bin/terraform -v
      - name: tf fmt
        run: .bin/terraform fmt -check -recursive
      - name: tf init
        run: .bin/terraform init -backend=false
      - name: tf validate
        run: .bin/terraform validate
      - name: tflint (setup)
        uses: terraform-linters/setup-tflint@v4
        with:
          github_token: ${{ github.token }}
      - name: tflint (run)
        env:
          # https://github.com/terraform-linters/tflint/blob/master/docs/user-guide/plugins.md#avoiding-rate-limiting
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          tflint --init
          tflint
  terraform-security:
    runs-on: ubuntu-latest
    if: inputs.checkov_enabled
    defaults:
      run:
        working-directory: ${{ inputs.workdir }}
    steps:
      - name: checkout
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
      - name: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: ${{ inputs.workdir }}
          framework: terraform
          download_external_modules: true
          quiet: true
