on:
  workflow_call:

name: terraform-docs
jobs:
  terraform-docs:
    runs-on: ubuntu-latest
    name: update docs
    steps:
      - name: checkout
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4
      - name: terraform-docs
        uses: terraform-docs/gh-actions@6de6da0cefcc6b4b7a5cbea4d79d97060733093c # v1.4.1
        with:
          working-dir: .
          output-file: README.md
          output-method: inject
          git-commit-message: "docs: update terraform docs"
          git-push: "true"
