on:
  workflow_call:

name: terraform-docs
jobs:
  terraform-docs:
    runs-on: ubuntu-latest
    name: update docs
    steps:
      - name: checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - name: terraform-docs
        uses: terraform-docs/gh-actions@v1.0.0
        with:
          working-dir: .
          output-file: README.md
          output-method: inject
          git-commit-message: "docs: update terraform docs"
          git-push: "true"
